### PR TITLE
Latest comic lookup

### PR DESCRIPTION
**Pull request by gebrek**
When 'latest' is in the comment body we have to look it up, but its
comic_id is not yet known. So use the value from the info.0.json for
the database, and use 0 as a placeholder.

### CODE REVIEW

**Comment by joeyvanlierop** [comment]
If a user comments with both "!latest" along with the current comic (for today it would be "!2258"), I believe a duplicate response would be added. This could potentially be solved by calling find_latest from within find_numbers like so:

```
def find_numbers(self, body, strict_match):
        ...

        if strict_match:
            numbers = re.findall(r"""(?i)(?x)       # Ignore case, comment mode
                                (?<= ! | \# )       # Must be preceded by an exclamation mark or a pound sign    
                                \d+                 # Matches the following numbers
                                """, body)

        else:
            numbers = re.findall(r"""(?i)(?x)       # Ignore case, comment mode   
                                \d+                 # Matches the following numbers
                                """, body)

        latest = self.find_latest(body, strict_match)
        if latest:
            numbers.append(LATEST)

        stripped_numbers = strip_leading_zeroes(numbers)
        unique_numbers = remove_duplicates(stripped_numbers)
        return unique_numbers
```

I am not 100% sure that this would work, but implementing some basic unit tests should provide the answer.

Let me know if you think this is a viable solution. Feel free to suggest a different approach if you think this is a poor way to avoid the duplication "bug".

Thanks for the contribution!

**Comment by gebrek** [comment]
Ah, didn't think of the duplication. First thought of looking up the latest comic and recording that but then there's a duplicate request. 

This would still create a duplicate result as you say, if the user has "!latest" and "!2258", because they're still different numbers (LATEST=0). You need some way to distinguish which comic_id is the latest one.

Off the top of my head the most request-efficient way would be to look it up at the right times and cache it. This would add an additional mechanism, but would produce code with less edge-cases I think.

Or you can do a look up for both !2258 and !latest then remove the duplicate from responses in handle_comment.

Sidenote: The duplicate result makes me wonder how !random would work too, if by chance it coincided with a specifically chosen comic_id

**Comment by joeyvanlierop** [comment]
> This would still create a duplicate result as you say, if the user has "!latest" and "!2258", because they're still different numbers (LATEST=0).

Whoops, totally slipped my mind.  

Perhaps adding a function "get_latest_comic_id" could be implemented to return the number of the latest comic. Additionally, it would probably be a good idea to rename the "find_x" functions to something more appropriate like "match_x". This would result in:

```
    def match_numbers(self, body, strict_match):
        ...

        if self.match_latest(body, strict_match):
            latest_comic_id = self.get_latest_comic_id()
            numbers.append(latest_comic_id)

        if strict_match:
            numbers += re.findall(r"""(?i)(?x)       # Ignore case, comment mode
                                 (?<= ! | \# )       # Must be preceded by an exclamation mark or a pound sign    
                                 \d+                 # Matches the following numbers
                                 """, body)
        else:
            numbers += re.findall(r"""(?i)(?x)       # Ignore case, comment mode   
                                 \d+                 # Matches the following numbers
                                 """, body)
        
        stripped_numbers = strip_leading_zeroes(numbers)
        unique_numbers = remove_duplicates(stripped_numbers)
        return unique_numbers

    def match_latest(self, body, strict_match):
        """
        Finds 'latest' in the body and returns True if it is.
        :param strict_match: Using the same rules as find_numbers
        """
        if strict_match:
            latest = re.findall(r"""(?i)(?<= ! | \# )latest""", body)
        else:
            latest = re.findall(r"""(?i)latest""", body)

        return bool(latest)

    def get_latest_comic_id(self):
        """
        Returns the id of the latest comic.
        """
        url = f"http://xkcd.com/info.0.json"
        response = requests.get(url)

        if response.status_code == 404:
            return None
        elif response is None:
            return None
        else:
            data = response.json()
            return data["num"]

    def get_comic(self, number):
        """
        Returns the JSON data of the comic with the given number.
        Returns none if there is no comic with the given number.
        """
        url = f"http://xkcd.com/{number}/info.0.json"
        response = requests.get(url)

        if response.status_code == 404:
            return None
        elif response is None:
            return None
        else:
            data = response.json()
            return data
```

Not the most clean, and it could probably be condensed down but I just wanted to throw so more ideas out there. Let me know what you think about this.

**Comment by gebrek** [comment]
I included the request as you've described it, and named the functions a little more appropriately. There's a little bit of code duplication with the http response checking, but I did abstract the pattern of looking for a given token (at the moment, some number or 'latest', but should be useful for 'random' as well).

Please let me know if this suffices! And thanks for starting the project.

**Comment by joeyvanlierop** [comment]
Thanks for the great work!

**Pull request merged**
